/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminDebugRouteImport } from './routes/admin-debug'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddBlogRouteImport } from './routes/add-blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminBlogsRouteImport } from './routes/admin/blogs'
import { Route as AdminAddBlogRouteImport } from './routes/admin/add-blog'
import { Route as BlogIdNewRouteImport } from './routes/blog.$id.new'
import { Route as AdminEditBlogIdRouteImport } from './routes/admin/edit-blog.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDebugRoute = AdminDebugRouteImport.update({
  id: '/admin-debug',
  path: '/admin-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBlogRoute = AddBlogRouteImport.update({
  id: '/add-blog',
  path: '/add-blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAddBlogRoute = AdminAddBlogRouteImport.update({
  id: '/add-blog',
  path: '/add-blog',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIdNewRoute = BlogIdNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BlogIdRoute,
} as any)
const AdminEditBlogIdRoute = AdminEditBlogIdRouteImport.update({
  id: '/edit-blog/$id',
  path: '/edit-blog/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-blog': typeof AddBlogRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-debug': typeof AdminDebugRoute
  '/admin-login': typeof AdminLoginRoute
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/admin/add-blog': typeof AdminAddBlogRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/services': typeof AdminServicesRoute
  '/blog/$id': typeof BlogIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/edit-blog/$id': typeof AdminEditBlogIdRoute
  '/blog/$id/new': typeof BlogIdNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-blog': typeof AddBlogRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-debug': typeof AdminDebugRoute
  '/admin-login': typeof AdminLoginRoute
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/admin/add-blog': typeof AdminAddBlogRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/services': typeof AdminServicesRoute
  '/blog/$id': typeof BlogIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/edit-blog/$id': typeof AdminEditBlogIdRoute
  '/blog/$id/new': typeof BlogIdNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-blog': typeof AddBlogRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-debug': typeof AdminDebugRoute
  '/admin-login': typeof AdminLoginRoute
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/admin/add-blog': typeof AdminAddBlogRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/services': typeof AdminServicesRoute
  '/blog/$id': typeof BlogIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/edit-blog/$id': typeof AdminEditBlogIdRoute
  '/blog/$id/new': typeof BlogIdNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-blog'
    | '/admin'
    | '/admin-dashboard'
    | '/admin-debug'
    | '/admin-login'
    | '/blog'
    | '/book'
    | '/contact'
    | '/services'
    | '/admin/add-blog'
    | '/admin/blogs'
    | '/admin/profile'
    | '/admin/services'
    | '/blog/$id'
    | '/admin/'
    | '/admin/edit-blog/$id'
    | '/blog/$id/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-blog'
    | '/admin-dashboard'
    | '/admin-debug'
    | '/admin-login'
    | '/blog'
    | '/book'
    | '/contact'
    | '/services'
    | '/admin/add-blog'
    | '/admin/blogs'
    | '/admin/profile'
    | '/admin/services'
    | '/blog/$id'
    | '/admin'
    | '/admin/edit-blog/$id'
    | '/blog/$id/new'
  id:
    | '__root__'
    | '/'
    | '/add-blog'
    | '/admin'
    | '/admin-dashboard'
    | '/admin-debug'
    | '/admin-login'
    | '/blog'
    | '/book'
    | '/contact'
    | '/services'
    | '/admin/add-blog'
    | '/admin/blogs'
    | '/admin/profile'
    | '/admin/services'
    | '/blog/$id'
    | '/admin/'
    | '/admin/edit-blog/$id'
    | '/blog/$id/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddBlogRoute: typeof AddBlogRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDebugRoute: typeof AdminDebugRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-debug': {
      id: '/admin-debug'
      path: '/admin-debug'
      fullPath: '/admin-debug'
      preLoaderRoute: typeof AdminDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-blog': {
      id: '/add-blog'
      path: '/add-blog'
      fullPath: '/add-blog'
      preLoaderRoute: typeof AddBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/add-blog': {
      id: '/admin/add-blog'
      path: '/add-blog'
      fullPath: '/admin/add-blog'
      preLoaderRoute: typeof AdminAddBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$id/new': {
      id: '/blog/$id/new'
      path: '/new'
      fullPath: '/blog/$id/new'
      preLoaderRoute: typeof BlogIdNewRouteImport
      parentRoute: typeof BlogIdRoute
    }
    '/admin/edit-blog/$id': {
      id: '/admin/edit-blog/$id'
      path: '/edit-blog/$id'
      fullPath: '/admin/edit-blog/$id'
      preLoaderRoute: typeof AdminEditBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAddBlogRoute: typeof AdminAddBlogRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditBlogIdRoute: typeof AdminEditBlogIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAddBlogRoute: AdminAddBlogRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditBlogIdRoute: AdminEditBlogIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogIdRouteChildren {
  BlogIdNewRoute: typeof BlogIdNewRoute
}

const BlogIdRouteChildren: BlogIdRouteChildren = {
  BlogIdNewRoute: BlogIdNewRoute,
}

const BlogIdRouteWithChildren =
  BlogIdRoute._addFileChildren(BlogIdRouteChildren)

interface BlogRouteChildren {
  BlogIdRoute: typeof BlogIdRouteWithChildren
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIdRoute: BlogIdRouteWithChildren,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddBlogRoute: AddBlogRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDebugRoute: AdminDebugRoute,
  AdminLoginRoute: AdminLoginRoute,
  BlogRoute: BlogRouteWithChildren,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
